### ISSUE TITLE
Recommendation strength: Log odds vs Percentage Points

### ISSUE THREAD

**Issue by peteowen1** [nflverse/nfl4th#8]
Not sure if this is the correct place for discussion, as new to Github, just point me in the right direction if not.

Seems like the main complaints with the bot currently are either lack of player-based info, or that recommendations seem weird when game is essentially over i.e. model almost always calls a decision a toss-up when win prob. is > 90%

Obviously harder to interpret log-odds instead of percentage points but if people are going to complain that the bot is too on the fence in these situations then maybe log-odds could be considered.

Just a thought, let me know what you think.

**Comment by guga31bb** [comment]
Yep I've received this log-odds suggestion from a lot of people and I think it's a good one. Planning to make this tweak soon-ish hopefully. Thank you!

(and yes this is the right place for discussion)

**Comment by guga31bb** [comment]
Okay tweaked it a bit here- we'll see how this looks https://github.com/guga31bb/fourth_calculator/commit/c5976eb9d1a9083d7abbf74c49c0c33b6d959c30#diff-767c762c3826abca436122d00b69b081f42d941865357a302013f9b2c9473ae1R52
